# Generated by Django 4.2 on 2023-04-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_call_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
