# Generated by Django 4.2 on 2023-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_call_telegram_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
