# Generated by Django 4.2 on 2023-04-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_call_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='is_active',
            field=models.BooleanField(default='True'),
        ),
    ]
