# Generated by Django 4.2 on 2023-04-13 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
