# Generated by Django 4.2 on 2023-04-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover',
        ),
    ]
