# Generated by Django 4.2 on 2023-04-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseimages',
            old_name='Course',
            new_name='course',
        ),
    ]
