# Generated by Django 4.2 on 2023-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_course_courseimages_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimages',
            options={'verbose_name_plural': 'Course Images'},
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/covers/'),
        ),
        migrations.AlterField(
            model_name='courseimages',
            name='image',
            field=models.ImageField(upload_to='images/course_images/'),
        ),
    ]
