# Generated by Django 4.2 on 2023-04-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_courseimages_options_alter_course_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='lorem ipsum'),
        ),
    ]
