# Generated by Django 4.2 on 2023-04-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('mentors', '0001_initial'),
        ('course', '0014_remove_course_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='category.language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mentors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='mentors.mentor'),
        ),
    ]
