# Generated by Django 4.2 on 2023-04-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('years_exp', models.IntegerField(default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='specialty', to='category.language')),
            ],
            options={
                'verbose_name': 'Ментор',
                'verbose_name_plural': 'Ментора',
            },
        ),
    ]
